Repository Team-OnDot/OnDot-Frontend, pull requests merged in 2024-02, with the labels that each got.

#27 [FEAT] #21 로그인, 회원가입 백엔드 연결 코드 작성
  package-lock.json
  package.json
  src/App.tsx
  src/components/interviewApply/ApplyInfoForm.tsx
  src/components/login/LoginForm.style.ts
  src/components/login/LoginForm.tsx
  src/components/signUp/GroupType.tsx
  src/components/signUp/SignUpForm.style.ts
  src/components/signUp/SignUpForm.tsx
  src/pages/login/Login.style.ts
  src/pages/login/Login.tsx
  src/pages/signUp/SignUpId.tsx
  src/recoil/SignUpAtoms.ts
Labels: feat, 제이피지

#33 [FIX] #32 폰트 굵기 문제 해결
  src/GlobalStyle.tsx
  src/components/calendar/Calendar.css
  src/components/groupProfile/GroupInfo.style.ts
  src/components/groupProfile/InterviewPreview.style.ts
  src/components/interviewApply/ApplyInfoForm.style.ts
  src/components/interviewApply/InterviewApply.style.ts
  src/components/interviewMake/TimeType.style.ts
  src/components/login/LoginForm.style.ts
  src/components/signUp/SignUpForm.style.ts
  src/components/timeTable/TimeTable.style.ts
  src/pages/groupProfile/GroupProfile.style.ts
  src/pages/groupProfile/GroupProfileSetting.style.ts
  src/pages/header/Header.style.ts
  src/pages/interviewApply/ApplyTime.style.ts
  src/pages/interviewApply/InterviewApply.style.ts
  src/pages/interviewMake/InterviewMake1.style.tsx
  src/pages/interviewMake/InterviewMake2.style.ts
  src/pages/interviewMake/InterviewMake3.style.tsx
  src/pages/interviewMake/InterviewMakeComplete.style.tsx
  src/pages/login/Login.style.ts
Labels: fix, 마크

#39 [FEAT] #31 PDF, PNG, 클립보드 복사 구현
  package-lock.json
  package.json
  public/images/clickedPdfIcon.svg
  public/images/clickedPngIcon.svg
  public/images/pdfIcon.svg
  public/images/pngIcon.svg
  src/App.tsx
  src/components/groupProfile/GroupInfo.style.ts
  src/components/interviewApply/InterviewApply.style.ts
  src/components/interviewApply/InterviewApplySide.tsx
  src/pages/header/Header.tsx
  src/pages/timeTableDown/TimeTableView3.style.ts
  src/pages/timeTableDown/TimeTableView3.tsx
Labels: feat, 제이피지

#35 [FIX] #34 타임테이블 관련 작업
  package-lock.json
  src/App.tsx
  src/components/interviewApply/ApplyInfoForm.tsx
  src/components/timeTable/TimeTable.style.ts
  src/components/timeTable/TimeTable.tsx
  src/pages/interviewApply/ApplyTime.style.ts
  src/pages/interviewApply/ApplyTime.tsx
  src/pages/interviewApply/InterviewApply.style.ts
  src/pages/interviewApply/InterviewApply.tsx
  src/pages/interviewApply/InterviewApplyComplete.tsx
  src/pages/interviewApply/InterviewApplyEditInfo1.tsx
  src/pages/interviewApply/InterviewApplyEditInfo2.tsx
  src/pages/interviewApply/InterviewApplyEnd.tsx
  src/pages/interviewApply/InterviewApplyInputInfo.tsx
  src/pages/interviewApply/InterviewApplyInputSchedule.tsx
  src/pages/interviewApply/InterviewApplyMain.tsx
  src/pages/interviewApply/InterviewApplyYet.tsx
  src/pages/interviewMake/InterviewMake2.tsx
Labels: fix, feat, 마크

#43 [FEAT] 로그인, 회원가입 백엔드 연결 및 헤더 반응형 구현
  package.json
  public/images/headerProfile.svg
  public/images/menuBtn.svg
  src/App.tsx
  src/components/groupProfile/GroupInfo.tsx
  src/components/header/Header.style.ts
  src/components/header/Header.tsx
  src/components/login/LoginForm.tsx
  src/components/signUp/GroupType.tsx
  src/components/signUp/SignUpForm.style.ts
  src/components/signUp/SignUpForm.tsx
  src/pages/header/Header.style.ts
  src/pages/header/Header.tsx
  src/pages/home/Home.styled.ts
  src/pages/login/Login.style.ts
  src/pages/login/Login.tsx
  src/recoil/SignUpAtoms.ts
Labels: fix, feat, 제이피지

#58 [FIX] #57 면접 생성 페이지 - 면접 진행 시간과 타임테이블 연동
  src/components/timeTable/TimeTable.tsx
  src/pages/interviewApply/inputSchedule/InterviewApplyInputSchedule.tsx
  src/pages/interviewMake/InterviewMake2.tsx
  src/pages/interviewTimetable/progress/TimeTableProgress.tsx
Labels: fix, 마크

#61 [FEAT] #56 면접 조회 API연결
  src/components/interviewPreview/InterviewPreview.style.ts
  src/components/interviewPreview/InterviewPreview.tsx
  src/components/login/LoginForm.tsx
  src/pages/groupProfile/GroupProfileMain.style.ts
  src/pages/groupProfile/GroupProfileMain.tsx
Labels: feat, 제이피지

#63 [FEAT] #56 면접 조회 API 연결
  src/App.tsx
  src/components/interviewPreview/InterviewPreview.style.ts
  src/components/interviewPreview/InterviewPreview.tsx
  src/index.tsx
  src/pages/findAccount/findPassword/FindPw2.tsx
  src/pages/groupProfile/GroupProfileMain.tsx
  src/pages/interviewMake/InterviewMake1.tsx
  src/recoil/interviewAtoms.ts
Labels: feat, 제이피지

#64 [FIX] 면접 현황 페이지 로직 변경 및 api 연결
  src/components/timeTable/TimeTable.tsx
  src/pages/interviewApply/inputSchedule/InterviewApplyInputSchedule.tsx
  src/pages/interviewTimetable/progress/TimeTableProgress.tsx
  src/recoil/interviewMake2Atom.ts
Labels: fix, feat, 마크
